version: "3"
services:

  postgres:
    image: "postgres:13.4-alpine"
    container_name: "db"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db"
    ports:
      - "35432:5432"