CREATE TABLE comments(
    id BIGSERIAL NOT NULL UNIQUE PRIMARY KEY,
    comment VARCHAR(1000) NOT NULL,
    task_id  BIGSERIAL NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    author_id  BIGSERIAL NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    write_date DATE NOT NULL
);