spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35432/postgres

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080

hashSecret: SECRET
complexity: 12

jwtSecret: "SECRET"
jwtSecretRefresh: "TASK_SECRET"

jwt.jwtExp: 900000
jwt.refreshExp: 86400000

allowed-origin: "http://localhost:8080"




